# This workflow will build a .NET project

name: Build
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

concurrency:
  group: trello-api-integration-tests
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore TrelloDotNet.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory TestResults --p:CollectCoverage=true --p:CoverletOutput=TestResults/ --p:CoverletOutputFormat=lcov --p:ExcludeByAttribute=ExcludeFromCodeCoverage
      working-directory: src/TrelloDotNet.Tests
      env:
        TrelloApiKey: ${{ secrets.TRELLOAPIKEY }}
        TrelloApiKey2: ${{ secrets.TRELLOAPIKEY2 }}
        TrelloApiKey3: ${{ secrets.TRELLOAPIKEY3 }}
        TrelloApiKey4: ${{ secrets.TRELLOAPIKEY4 }}
        TrelloApiKey5: ${{ secrets.TRELLOAPIKEY5 }}
        TrelloToken: ${{ secrets.TRELLOTOKEN }}
        TrelloToken2: ${{ secrets.TRELLOTOKEN2 }}
        TrelloToken3: ${{ secrets.TRELLOTOKEN3 }}
        TrelloToken4: ${{ secrets.TRELLOTOKEN4 }}
        TrelloToken5: ${{ secrets.TRELLOTOKEN5 }}
    - name: Upload test diagnostics
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: src/TrelloDotNet.Tests/TestResults
        retention-days: 7
    - name: Publish coverage report to coveralls.io   
      uses: coverallsapp/github-action@master   
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        path-to-lcov: src/TrelloDotNet.Tests/TestResults/coverage.info
    - name: Publish to NuGet if needed
      run: dotnet nuget push **\*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
